### ISSUE TITLE
Note to Chris - Thank you - Inspired me to build another containerized dev repo

### ISSUE THREAD

**Issue by TomFreudenberg** [chris-crone/containerized-go-dev#10]
Hi Chris @chris-crone 

thanks a lot for your open project and the content in your blogs.

Maybe you also like to check my repo at https://github.com/TomFreudenberg/golang-cli-cmd-dev-starter

It may give some additional points.

Cheers
Tom

**Comment by chris-crone** [comment]
Sorry for the tardy reply but you're welcome! Glad that you managed to make use of it
