### ISSUE TITLE
Container image misses `go` and `make` commands

### ISSUE THREAD

**Issue by felipecruz91** [chris-crone/containerized-go-dev#12]
Hi,

First of all, thank you for providing this repo as an example of a containerized Go dev environment!

When launched this repo as a Dev Environment in Docker Desktop 3.5.2 (66501) and opened in VSCode, both `go` and `make` are missing from the container image:

```
vscode ➜ /com.docker.devenvironments.code (main) $ go version
bash: go: command not found
vscode ➜ /com.docker.devenvironments.code (main) $ make
bash: make: command not found
```

Could it be because the main language of this repository is `Dockerfile` instead of `Go`?

**Comment by chris-crone** [comment]
Oh, good catch! We should probably add make to the Dev Envs containers
