### ISSUE TITLE
Fails for version 1.16

### ISSUE THREAD

**Issue by themathmagician** [chris-crone/containerized-go-dev#7]
If I bumb the FROM to version 1.16, the docker build fails with the following message:
```
 > [build 4/4] RUN go build -o /out/example .:
#8 0.337 go: cannot find main module
```
Can be fixed by changing the RUN in the dockerfile:
```
RUN go env -w GO111MODULE=auto && go build -o /out/example .
```

**Comment by chris-crone** [comment]
Thanks the report @themathmagician!

I'm not seeing that issue in the bump that I put up in [a PR](https://github.com/chris-crone/containerized-go-dev/pull/8).

Do you have any local changes?

**Comment by themathmagician** [comment]
No changes, just a plain vanilla hello world project.
If you follow the example from bare minimum, you need the GO111MODULE auto, OR to have a mod file present.
But running `go mod init` is in the second part of the tutorial.

**Comment by StudioEtrange** [comment]
any status on this @chris-crone  ? 
thx

**Comment by chris-crone** [comment]
Sorry for the slow reply, I see what you mean @themathmagician: The first blog post's instructions do not work with Go 1.16+.

I recommend reading the blog posts to understand what the patterns do and then to use this git repo for code that works. The repo works as it has a `go.mod` file. I've also just bumped it to 1.17 in this [PR](#13).
